{
 "title": "Rockset Overview",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "rockset_leaf_cpu_utilization_percentage"
    }
   },
   {
    "name": "virtual_instance",
    "label": "Virtual Instance",
    "query": {
     "query": "rockset_leaf_cpu_utilization_percentage{job=\"$job\"}"
    }
   },
   {
    "name": "Workspace",
    "label": "Workspace",
    "query": {
     "query": "rockset_collection_data_process_latency_bucket{job=\"$job\"}"
    }
   },
   {
    "name": "Collection",
    "label": "Collection",
    "query": {
     "query": "rockset_collection_data_process_latency_bucket{job=\"$job\", workspace_name=~\"$Workspace\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Ingestion Latency Distribution",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(rockset_collection_data_process_latency_bucket{workspace_name=~\"$Workspace\", collection_name=~\"$Collection\"}[2m]) + rate(rockset_collection_data_discovery_latency_bucket{workspace_name=~\"$Workspace\", collection_name=~\"$Collection\"}[2m])\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Num Collections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rockset_collections{job=~\"$job\"}",
     "legendFormat": "{{workspace_name}}"
    }
   ]
  },
  {
   "title": "Collection Size (GB)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, rockset_collection_size_bytes{job=~\"$job\"}/1024/1024)",
     "legendFormat": "{{workspace_name}}.{{collection_name}}"
    }
   ]
  },
  {
   "title": "Num Documents",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, rockset_collection_documents{job=~\"$job\"})",
     "legendFormat": "{{workspace_name}}.{{collection_name}}"
    }
   ]
  },
  {
   "title": "Ingestion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(rockset_collection_total_ingest_bytes{job=~\"$job\"}[30s]) * ((rate(rockset_collection_total_ingest_bytes{job=~\"$job\"}[30s]) > 0) ^0)",
     "legendFormat": "{{workspace_name}}.{{collection_name}}"
    }
   ]
  },
  {
   "title": "Ingestion Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(rockset_collection_parse_errors{job=~\"$job\"}[30s]) * ((rate(rockset_collection_parse_errors{job=~\"$job\"}[30s]) > 0.5) ^0)",
     "legendFormat": "{{workspace_name}}.{{collection_name}}"
    }
   ]
  },
  {
   "title": "Collection Data Discovery Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, workspace_name, collection_name, job) (rate(rockset_collection_data_discovery_latency_bucket{job=\"$job\"}[1m]))) * (histogram_quantile(0.99, sum by(le, workspace_name, collection_name, job) ((rate(rockset_collection_data_discovery_latency_bucket{job=\"$job\"}[1m]))) > 0) ^0)",
     "legendFormat": "p99.{{workspace_name}}.{{collection_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, workspace_name, collection_name, job) (rate(rockset_collection_data_discovery_latency_bucket{job=\"$job\"}[1m]))) * (histogram_quantile(0.95, sum by(le, workspace_name, collection_name, job) ((rate(rockset_collection_data_discovery_latency_bucket{job=\"$job\"}[1m]))) > 0) ^0)",
     "legendFormat": "p95.{{workspace_name}}.{{collection_name}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le, workspace_name, collection_name, job) (rate(rockset_collection_data_discovery_latency_bucket{job=\"$job\"}[1m]))) * (histogram_quantile(0.5, sum by(le, workspace_name, collection_name, job) ((rate(rockset_collection_data_discovery_latency_bucket{job=\"$job\"}[1m]))) > 0) ^0)",
     "legendFormat": "p50.{{workspace_name}}.{{collection_name}}"
    },
    {
     "expr": "sum(rate(rockset_collection_data_discovery_latency_sum{job=\"$job\"}[1m])) by (workspace_name, collection_name, job) / sum(rate(rockset_collection_data_discovery_latency_count{job=\"$job\"}[1m])) by (workspace_name, collection_name, job) ",
     "legendFormat": "avg.{{workspace_name}}.{{collection_name}}"
    }
   ]
  },
  {
   "title": "Collection Data Process Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, workspace_name, collection_name, job) (rate(rockset_collection_data_process_latency_bucket{job=\"$job\"}[30s]))) * (histogram_quantile(0.99, sum by(le, workspace_name, collection_name, job) ((rate(rockset_collection_data_process_latency_bucket{job=\"$job\"}[30s]))) > 0) ^0)",
     "legendFormat": "p99 {{workspace_name}}.{{collection_name}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, workspace_name, collection_name, job) (rate(rockset_collection_data_process_latency_bucket{job=\"$job\"}[30s]))) * (histogram_quantile(0.95, sum by(le, workspace_name, collection_name, job) ((rate(rockset_collection_data_process_latency_bucket{job=\"$job\"}[30s]))) > 0) ^0)",
     "legendFormat": "p95 {{workspace_name}}.{{collection_name}}"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le, workspace_name, collection_name, job) (rate(rockset_collection_data_process_latency_bucket{job=\"$job\"}[30s]))) * (histogram_quantile(0.50, sum by(le, workspace_name, collection_name, job) ((rate(rockset_collection_data_process_latency_bucket{job=\"$job\"}[30s]))) > 0) ^0)",
     "legendFormat": "p50 {{workspace_name}}.{{collection_name}}"
    }
   ]
  },
  {
   "title": "Total Data Process Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, job) (rate(rockset_data_process_latency_bucket{job=~\"$job\"}[30s]))) * ((histogram_quantile(0.95, sum by(le, job) (rate(rockset_data_process_latency_bucket{job=~\"$job\"}[30s])) > 0) ^0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(rockset_queries{virtual_instance_id=~\"$virtual_instance\", job=~\"$job\"}[30s])",
     "legendFormat": "{{job}} - {{virtual_instance_id}}"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, virtual_instance_id) (rate(rockset_query_latency_seconds_bucket{virtual_instance_id=~\"$virtual_instance\", job=~\"$job\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Admission Latency Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, virtual_instance_id) (rate(rockset_query_admission_latency_seconds_bucket{virtual_instance_id=~\"$virtual_instance\", job=~\"$job\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "rockset_query_queue_size{job=~\"$job\", virtual_instance_id=~\"$virtual_instance\"}",
     "legendFormat": "{{job}} - {{virtual_instance_id}}"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "rate(rockset_query_errors{job=~\"$job\", virtual_instance_id=~\"$virtual_instance\"}[30s])",
     "legendFormat": "Error Code: {{error_code}}"
    }
   ]
  },
  {
   "title": "Query Lambda Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "rate(rockset_query_lambda_queries{job=~\"$job\", virtual_instance_id=~\"$virtual_instance\"}[30s]) * ((rate(rockset_query_lambda_queries{job=~\"$job\", virtual_instance_id=~\"$virtual_instance\"}[30s]) > 0) ^0)",
     "legendFormat": "{{workspace_name}}.{{query_lambda}}.{{tag}}"
    }
   ]
  },
  {
   "title": "Query Lambda Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(virtual_instance_id, le) (rate(rockset_query_lambda_latency_seconds_bucket{job=~\"$job\", virtual_instance_id=~\"$virtual_instance\"}[30s])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Lambda Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "rate(rockset_query_lambda_errors{job=~\"$job\", virtual_instance_id=~\"$virtual_instance\"}[30s])",
     "legendFormat": "{{error_code}}: {{workspace_name}}.{{query_lambda}}.{{tag}}"
    }
   ]
  },
  {
   "title": "Virtual Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Leaf CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "rockset_leaf_cpu_utilization_percentage{job=~\"$job\", virtual_instance_id=~\"$virtual_instance\"}",
     "legendFormat": "{{job}} - {{virtual_instance_id}}",
     "queryParamStart": ":startTime",
     "queryParamStop": ":stopTime",
     "queryText": "-- sample query\nSELECT\n  TIME_BUCKET(MINUTES(5), _events._event_time) AS _event_time,\n  COUNT(_events.type) AS value\nFROM\n  commons._events\n-- you MUST specify a WHERE clause which scopes the query using :startTime and :stopTime\nWHERE\n  _events._event_time > :startTime AND\n  _events._event_time < :stopTime\nGROUP BY\n  _event_time\nORDER BY\n  _event_time",
     "queryTimeField": "_event_time"
    }
   ]
  },
  {
   "title": "Leaf Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "rockset_leaf_memory_utilization_percentage{job=~\"$job\", virtual_instance_id=~\"$virtual_instance\"}",
     "legendFormat": "{{job}} - {{virtual_instance_id}}",
     "queryParamStart": ":startTime",
     "queryParamStop": ":stopTime",
     "queryText": "-- sample query\nSELECT\n  TIME_BUCKET(MINUTES(5), _events._event_time) AS _event_time,\n  COUNT(_events.type) AS value\nFROM\n  commons._events\n-- you MUST specify a WHERE clause which scopes the query using :startTime and :stopTime\nWHERE\n  _events._event_time > :startTime AND\n  _events._event_time < :stopTime\nGROUP BY\n  _event_time\nORDER BY\n  _event_time",
     "queryTimeField": "_event_time"
    }
   ]
  },
  {
   "title": "Aggregator CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "rockset_agg_cpu_utilization_percentage{job=~\"$job\", virtual_instance_id=~\"$virtual_instance\"}",
     "legendFormat": "{{job}} - {{virtual_instance_id}}",
     "queryParamStart": ":startTime",
     "queryParamStop": ":stopTime",
     "queryText": "-- sample query\nSELECT\n  TIME_BUCKET(MINUTES(5), _events._event_time) AS _event_time,\n  COUNT(_events.type) AS value\nFROM\n  commons._events\n-- you MUST specify a WHERE clause which scopes the query using :startTime and :stopTime\nWHERE\n  _events._event_time > :startTime AND\n  _events._event_time < :stopTime\nGROUP BY\n  _event_time\nORDER BY\n  _event_time",
     "queryTimeField": "_event_time"
    }
   ]
  },
  {
   "title": "Aggregator Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "rockset_agg_memory_utilization_percentage{job=~\"$job\", virtual_instance_id=~\"$virtual_instance\"}",
     "legendFormat": "{{job}} - {{virtual_instance_id}}",
     "queryParamStart": ":startTime",
     "queryParamStop": ":stopTime",
     "queryText": "-- sample query\nSELECT\n  TIME_BUCKET(MINUTES(5), _events._event_time) AS _event_time,\n  COUNT(_events.type) AS value\nFROM\n  commons._events\n-- you MUST specify a WHERE clause which scopes the query using :startTime and :stopTime\nWHERE\n  _events._event_time > :startTime AND\n  _events._event_time < :stopTime\nGROUP BY\n  _event_time\nORDER BY\n  _event_time",
     "queryTimeField": "_event_time"
    }
   ]
  }
 ]
}